Invitation
Kylian2/vote-right pull request #50
Opened 2024-12-27 19:03 UTC by Laren21

2024-12-27 20:05 UTC, Kylian2 requested changes
J'ai laissé des commentaires à certains endroit du code, peux-tu y répondre. Il faut aussi que tu mettes à jour la documentation de l'API avec tes endpoints et les modifications que tu as fait à certains. Pour éditer le fichier tu peux aller sur le site stoplight.io.

2024-12-27 22:33 UTC, Kylian2 commented on backend/models/invitation.php
> +    public int $INV_id_VC;
Le type n'est pas bon, je suppose qu'il faut mettre `string`

2024-12-27 22:38 UTC, Laren21 commented on backend/route/routes.php
> +Router::get('/communities/{id}/themes', 'communityController@themes', false);
ok

2024-12-27 22:39 UTC, Laren21 commented on backend/route/routes.php
> +Router::get('/communities/{id}', 'communityController@show', false);
ok

2024-12-27 22:41 UTC, Laren21 commented on backend/controllers/invitationController.php
> +     * ex de données acceptées :
Je fais tout dans une seule fonction donc il me faut toutes les informations par la méthode POST pour effectuer les opérations nécessaires sur la base de données, il me faut donc : le code, la communauté, et le numéro du receveur de l'invitation

2024-12-27 22:41 UTC, Laren21 commented on backend/models/invitation.php
> +    public static function accept(array $params){
ok

2024-12-27 22:41 UTC, Laren21 commented on backend/models/invitation.php
> +    public static function reject(array $params){
ok

2024-12-27 22:41 UTC, Laren21 commented on backend/models/invitation.php
> +    public int $INV_id_VC;
ok

2024-12-27 22:44 UTC, Kylian2 commented on backend/route/routes.php
> +Router::post('/invitation/{id}/reject', 'invitationController@rejected');
invitation**s**. Il faut mettre les ressources au pluriel.

2024-12-27 23:10 UTC, Laren21 commented on backend/controllers/invitationController.php
> +        json_encode($verifCode);
C'était durant les tests pour visualiser les sorties des fonctions des modèles j'ai dû oublier de les enlever.

2024-12-28 00:14 UTC, Kylian2 commented on backend/controllers/invitationController.php
> +     * ex de données acceptées :
Tu peux avoir ces informations à partir de l'invitation normalement ?

2024-12-29 20:33 UTC, Kylian2 approved these changes

2024-12-29 20:33 UTC, merged